# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ccuscode', models.CharField(db_column='cCusCode', max_length=20, primary_key=True, serialize=False)),
                ('ccusname', models.CharField(blank=True, db_column='cCusName', max_length=98, null=True)),
                ('ccusabbname', models.CharField(db_column='cCusAbbName', max_length=60)),
            ],
            options={
                'db_table': 'Customer',
                'managed': False,
            },
        ),
    ]
